//! `clave setup` (§6.8/§7): make the machine ready — generated session
//! config + layout in ~/.local/share/clave/, Claude hooks merged into
//! ~/.claude/settings.json (ADDITIVELY — the file may be a dotfiles symlink;
//! we edit through it and never clobber existing hooks), and Zellij's
//! permission cache pre-seeded (grants are all-or-nothing and the in-bar
//! prompt is unanswerable — S1/S2).

use std::path::PathBuf;

use anyhow::{Context, Result};

/// Where clave's generated artifacts live. NOT the repo: these files embed
/// machine-absolute paths (the wasm location) and the repo is public.
pub fn data_dir() -> Result<PathBuf> {
    Ok(dirs::home_dir().context("home")?.join(".local/share/clave"))
}

pub fn wasm_path() -> Result<PathBuf> {
    Ok(data_dir()?.join("clave-bar.wasm"))
}

/// §6.6's exact permission set. Keep THIS list, load()'s request_permission
/// call, and the seeded cache in lockstep — a partial cache match raises the
/// unanswerable prompt and withholds everything.
pub const BAR_PERMISSIONS: [&str; 4] = [
    "ReadCliPipes",
    "ChangeApplicationState",
    "ReadApplicationState",
    "RunCommands",
];

/// The clave session config: Alt keybinds in shared_among normal+locked
/// (invariant #6 — they must fire while Claude has focus), defaults kept.
pub fn config_kdl(wasm: &str) -> String {
    let nav = |payload: &str| {
        // Trailing `;` after the child block is REQUIRED: zellij's KDL parser
        // rejects a `}`-closed node that isn't terminated before the enclosing
        // bind-block `}` (found live in Task 9 C1 — `zellij setup --check`
        // failed on exactly these lines while the `;`-terminated Alt+a/Alt+c
        // forms parsed fine).
        format!("MessagePlugin \"file:{wasm}\" {{ name \"clave-nav\"; payload \"{payload}\"; }};")
    };
    let mut binds = String::new();
    binds.push_str(
        "        bind \"Alt a\" { Run \"clave\" \"add\" { floating true; close_on_exit true; }; }\n",
    );
    binds.push_str(&format!(
        "        bind \"Alt c\" {{ MessagePlugin \"file:{wasm}\" {{ name \"clave-toggle\"; }}; }}\n"
    ));
    binds.push_str("        bind \"Alt w\" { CloseTab; }\n");
    // Alt+↓/↑ walk the DISPLAYED list (§6.6 revised 2026-07-08: rows only
    // reorder on user commitments, never on focus — so walking the visible
    // order is stable, no ping-pong). Executor-gated in the plugin: only the
    // active instance (fresh tab set, the bar being read) computes the step.
    binds.push_str(&format!(
        "        bind \"Alt j\" \"Alt Down\" {{ {} }}\n",
        nav("{\\\"dir\\\":\\\"next\\\"}")
    ));
    binds.push_str(&format!(
        "        bind \"Alt k\" \"Alt Up\" {{ {} }}\n",
        nav("{\\\"dir\\\":\\\"prev\\\"}")
    ));
    // True alt-tab (last two focused tabs) is NATIVE — server-side truth.
    // Alt+o = native ToggleTab PLUS a clave-organic pipe: the pipe arms the
    // bounded beacon announce (the newly-active instance's next TabUpdate
    // announces it — rounds 11–12: unbounded self-diagnosed announces
    // stormed; organic switches must be explicitly signalled).
    binds.push_str(&format!(
        "        bind \"Alt o\" {{ ToggleTab; MessagePlugin \"file:{wasm}\" {{ name \"clave-organic\"; }}; }}\n"
    ));
    for n in 1..=9 {
        binds.push_str(&format!(
            "        bind \"Alt {n}\" {{ {} }}\n",
            nav(&format!("{{\\\"row\\\":{n}}}"))
        ));
    }
    format!(
        "// GENERATED by `clave setup` — regenerate, don't hand-edit.\n\
         // clear-defaults=false: stock zellij behaviour stays; clave only ADDS.\n\
         keybinds clear-defaults=false {{\n\
         \x20   shared_among \"normal\" \"locked\" {{\n{binds}\x20   }}\n\
         }}\n"
    )
}

/// The session layout: EVERY tab gets the bar via default_tab_template
/// (§6.8). Task 9 checkpoint C6 validates the template survives real use;
/// fallback = per-tab panes + a new-tab keybind with an explicit layout.
pub fn layout_kdl(wasm: &str) -> String {
    // split_direction="vertical" goes ON the template node, with `pane` and
    // `children` as DIRECT children (both Task 9 C1 findings):
    // 1. zellij stacks siblings horizontally (rows) by default — without
    //    vertical split the bar is a 26-ROW strip across the top;
    // 2. `children` must NOT be nested inside a wrapper pane: the empty/new-
    //    tab fill path (zellij-utils kdl_layout_parser.rs:1748, v0.44.3) only
    //    inserts the default pane at the template's TOP-LEVEL
    //    external_children_index — it does not recurse — so a nested
    //    `children` yields tabs with no terminal at all.
    format!(
        "// GENERATED by `clave setup` — regenerate, don't hand-edit.\n\
         layout {{\n\
         \x20   default_tab_template split_direction=\"vertical\" {{\n\
         \x20       pane size=26 borderless=true {{\n\
         \x20           plugin location=\"file:{wasm}\"\n\
         \x20       }}\n\
         \x20       children\n\
         \x20   }}\n\
         \x20   tab name=\"clave\" focus=true\n\
         }}\n"
    )
}

/// Additively merge clave's hook registrations into a settings.json value.
/// Never touches existing entries; skips events already carrying our command.
pub fn merge_hooks(settings: &mut serde_json::Value, clave_bin: &str) -> bool {
    // The §6.5 state machine's input events. PermissionRequest/StopFailure
    // are handled IF the CLI sends them, but registration sticks to the
    // documented set; Notification covers the needs-you cases.
    const EVENTS: [&str; 4] = ["UserPromptSubmit", "Stop", "Notification", "SessionEnd"];
    let mut changed = false;
    let hooks = settings
        .as_object_mut()
        .map(|o| o.entry("hooks").or_insert_with(|| serde_json::json!({})))
        .expect("settings.json root must be an object");
    for ev in EVENTS {
        let cmd = format!("{clave_bin} hook {ev}");
        let arr = hooks
            .as_object_mut()
            .expect("hooks must be an object")
            .entry(ev)
            .or_insert_with(|| serde_json::json!([]));
        let entries = arr.as_array_mut().expect("hook event must be an array");
        let present = entries.iter().any(|e| {
            e["hooks"]
                .as_array()
                .is_some_and(|hs| hs.iter().any(|h| h["command"] == serde_json::json!(cmd)))
        });
        if !present {
            entries.push(serde_json::json!({
                "hooks": [ { "type": "command", "command": cmd } ]
            }));
            changed = true;
        }
    }
    changed
}

/// Zellij's permission cache location (verified on this machine in S1).
pub fn permissions_cache_path() -> Result<PathBuf> {
    let home = dirs::home_dir().context("home")?;
    if cfg!(target_os = "macos") {
        Ok(home.join("Library/Caches/org.Zellij-Contributors.Zellij/permissions.kdl"))
    } else {
        Ok(home.join(".cache/zellij/permissions.kdl"))
    }
}

/// Merge our grant into the cache text, preserving everyone else's entries.
/// Format (verified against zellij 0.44.3 PermissionCache::to_string): one
/// quoted-location node per plugin, children = PermissionType names. We
/// remove any existing clave-bar nodes (both key forms) then append fresh
/// ones — replace-not-accumulate keeps re-runs idempotent even when the
/// permission set changes (the S2 lesson).
pub fn merge_permissions_kdl(existing: &str, wasm_abs: &str) -> String {
    let keys = [format!("\"file:{wasm_abs}\""), format!("\"{wasm_abs}\"")];
    let mut out = String::new();
    let mut skipping = false;
    for line in existing.lines() {
        let t = line.trim_start();
        if !skipping && keys.iter().any(|k| t.starts_with(k.as_str())) {
            skipping = true; // drop this node…
        }
        if skipping {
            if t.trim_end().ends_with('}') {
                skipping = false; // …through its closing brace
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    for key in keys {
        out.push_str(&format!("{key} {{\n"));
        for p in BAR_PERMISSIONS {
            out.push_str(&format!("    {p}\n"));
        }
        out.push_str("}\n");
    }
    out
}

/// The whole setup weave. Idempotent by construction — every part merges.
pub fn run_setup() -> Result<()> {
    let dir = data_dir()?;
    std::fs::create_dir_all(&dir)?;
    let wasm = wasm_path()?;
    let wasm_str = wasm.to_str().context("wasm path")?;
    anyhow::ensure!(
        wasm.exists(),
        "{} missing — run `just install` first (it copies the built wasm here)",
        wasm.display()
    );
    std::fs::write(dir.join("config.kdl"), config_kdl(wasm_str))?;
    std::fs::write(dir.join("layout.kdl"), layout_kdl(wasm_str))?;

    // Hooks: read-merge-write ~/.claude/settings.json. The path may be a
    // symlink into a dotfiles repo — fs::read/write follow it, which is
    // exactly what we want (§6.5).
    let settings_path = dirs::home_dir()
        .context("home")?
        .join(".claude/settings.json");
    let mut settings: serde_json::Value = match std::fs::read(&settings_path) {
        Ok(b) => serde_json::from_slice(&b).context("parsing ~/.claude/settings.json")?,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::json!({}),
        Err(e) => return Err(e).context("reading settings.json"),
    };
    if merge_hooks(&mut settings, "clave") {
        std::fs::write(&settings_path, serde_json::to_vec_pretty(&settings)?)?;
        println!("hooks merged into {}", settings_path.display());
    } else {
        println!("hooks already registered");
    }

    // Permissions pre-seed (§7): merge, preserving other plugins.
    let cache = permissions_cache_path()?;
    if let Some(parent) = cache.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let existing = std::fs::read_to_string(&cache).unwrap_or_default();
    std::fs::write(&cache, merge_permissions_kdl(&existing, wasm_str))?;
    println!("permissions seeded in {}", cache.display());
    Ok(())
}

/// Does `zellij list-sessions -n` output show `name` as a LIVE session?
/// EXITED is not live: attaching resurrects a fresh session whose tab_ids
/// restart from scratch.
pub fn session_is_live(list_output: &str, name: &str) -> bool {
    list_output
        .lines()
        .any(|l| l.split_whitespace().next() == Some(name) && !l.contains("EXITED"))
}

/// Bare `clave`: attach-or-create the dedicated session with OUR config +
/// layout (§6.8 — the user's global zellij config is never touched).
pub fn launch_session() -> Result<()> {
    let dir = data_dir()?;
    let (config, layout) = (dir.join("config.kdl"), dir.join("layout.kdl"));
    anyhow::ensure!(
        config.exists() && layout.exists(),
        "run `clave setup` first"
    );
    // §6.6 hygiene: tab_ids are SESSION-scoped, so when we're about to
    // CREATE (not re-attach) the session, drop the previous session's tab
    // timeline — reused ids would inherit dead tabs' commitments. Best
    // effort: list-sessions exits non-zero when no sessions exist at all.
    let live = std::process::Command::new("zellij")
        .args(["list-sessions", "-n"])
        .output()
        .map(|o| session_is_live(&String::from_utf8_lossy(&o.stdout), "clave"))
        .unwrap_or(false);
    if !live {
        crate::store::clear_tab_timeline(&crate::store::store_paths()?)?;
    }
    use std::os::unix::process::CommandExt;
    let err = std::process::Command::new("zellij")
        .arg("--config")
        .arg(&config)
        .arg("--layout")
        .arg(&layout)
        .args(["attach", "--create", "clave"])
        .exec();
    Err(anyhow::anyhow!("exec zellij failed: {err}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_is_live_reads_zellij_list_sessions() {
        // `zellij list-sessions -n` lines: `<name> [Created …]`, with
        // ` (EXITED - attach to resurrect)` appended for dead sessions.
        // EXITED counts as NOT live: attach resurrects a FRESH session whose
        // tab_ids restart, so the stale timeline must be cleared then too.
        let out = "chat [Created 5h ago]\nclave [Created 2m ago]\n";
        assert!(session_is_live(out, "clave"));
        let out = "clave [Created 2h ago] (EXITED - attach to resurrect)\n";
        assert!(!session_is_live(out, "clave"));
        // No sessions at all (list-sessions exits non-zero → empty string).
        assert!(!session_is_live("", "clave"));
        // Name must match the whole first token, not a prefix.
        assert!(!session_is_live("clave-dev [Created 1m ago]\n", "clave"));
    }

    #[test]
    fn hooks_merge_is_additive_and_idempotent() {
        // Existing user hook MUST survive (§6.5: never clobber).
        let mut v: serde_json::Value = serde_json::json!({
            "hooks": { "Stop": [ { "hooks": [ { "type": "command", "command": "my-bell" } ] } ] }
        });
        assert!(merge_hooks(&mut v, "clave"));
        let stops = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stops.len(), 2); // user's + ours
        assert_eq!(stops[0]["hooks"][0]["command"], "my-bell");
        assert_eq!(stops[1]["hooks"][0]["command"], "clave hook Stop");
        // Every event we need is registered.
        for ev in ["UserPromptSubmit", "Notification", "SessionEnd"] {
            assert!(v["hooks"][ev].as_array().is_some(), "{ev} missing");
        }
        // Second run: no change, no duplicates.
        assert!(!merge_hooks(&mut v, "clave"));
        assert_eq!(v["hooks"]["Stop"].as_array().unwrap().len(), 2);
    }

    #[test]
    fn permissions_merge_seeds_both_key_forms_and_preserves_others() {
        let existing = "\"file:/other/plugin.wasm\" {\n    ReadCliPipes\n}\n";
        let merged = merge_permissions_kdl(existing, "/data/clave-bar.wasm");
        // Other plugin untouched:
        assert!(merged.contains("/other/plugin.wasm"));
        // Both key forms present (S1/S2: key form matters):
        assert!(merged.contains("\"file:/data/clave-bar.wasm\""));
        assert!(merged.contains("\"/data/clave-bar.wasm\""));
        // The EXACT §6.6 set under each:
        for p in BAR_PERMISSIONS {
            assert!(
                merged.matches(p).count() >= 2,
                "{p} missing from a key form"
            );
        }
        // Idempotent: re-merging replaces our blocks, not duplicates them.
        let again = merge_permissions_kdl(&merged, "/data/clave-bar.wasm");
        assert_eq!(again.matches("file:/data/clave-bar.wasm").count(), 1);
    }

    #[test]
    fn generated_kdl_carries_the_wasm_path_and_alt_keys() {
        let cfg = config_kdl("/data/clave-bar.wasm");
        for key in [
            "Alt a", "Alt c", "Alt w", "Alt j", "Alt k", "Alt 1", "Alt 9",
        ] {
            assert!(
                cfg.contains(&format!("bind \"{key}\"")) || cfg.contains(&format!("\"{key}\"")),
                "{key} unbound"
            );
        }
        assert!(cfg.contains("shared_among \"normal\" \"locked\"")); // invariant #6
        assert!(cfg.contains("clave-nav") && cfg.contains("clave-toggle"));
        let lay = layout_kdl("/data/clave-bar.wasm");
        assert!(lay.contains("default_tab_template"));
        assert!(lay.contains("file:/data/clave-bar.wasm"));
        // Regression (Task 9 C1): without the vertical wrapper the bar is a
        // 26-ROW strip on top, not a 26-col LEFT column.
        assert!(lay.contains("split_direction=\"vertical\""));
    }
}
