//! `clave setup` (§6.8/§7): make the machine ready — generated session
//! config + layout in ~/.local/share/clave/, Claude hooks merged into
//! ~/.claude/settings.json (ADDITIVELY — the file may be a dotfiles symlink;
//! we edit through it and never clobber existing hooks), and Zellij's
//! permission cache pre-seeded (grants are all-or-nothing and the in-bar
//! prompt is unanswerable — S1/S2).

use std::path::PathBuf;

use anyhow::{Context, Result};

/// Where clave's generated artifacts live. NOT the repo: these files embed
/// machine-absolute paths (the wasm location) and the repo is public.
/// `$CLAVE_DATA_DIR` overrides the whole dir (spec §6.9: the dev harness sandboxes the store).
pub fn data_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("home")?;
    let default = home.join(".local").join("share").join("clave");
    Ok(crate::env::dir_from(
        std::env::var("CLAVE_DATA_DIR").ok(),
        default,
    ))
}

pub fn wasm_path() -> Result<PathBuf> {
    Ok(data_dir()?.join("clave-bar.wasm"))
}

/// §6.6's exact permission set. Keep THIS list, load()'s request_permission
/// call, and the seeded cache in lockstep — a partial cache match raises the
/// unanswerable prompt and withholds everything.
pub const BAR_PERMISSIONS: [&str; 4] = [
    "ReadCliPipes",
    "ChangeApplicationState",
    "ReadApplicationState",
    "RunCommands",
];

/// The clave session config: Alt keybinds in shared_among normal+locked
/// (invariant #6 — they must fire while Claude has focus), defaults kept.
pub fn config_kdl(wasm: &str) -> String {
    let nav = |payload: &str| {
        // Trailing `;` after the child block is REQUIRED: zellij's KDL parser
        // rejects a `}`-closed node that isn't terminated before the enclosing
        // bind-block `}` (found live in Task 9 C1 — `zellij setup --check`
        // failed on exactly these lines while the `;`-terminated Alt+a/Alt+c
        // forms parsed fine).
        format!("MessagePlugin \"file:{wasm}\" {{ name \"clave-nav\"; payload \"{payload}\"; }};")
    };
    let mut binds = String::new();
    binds.push_str(
        "        bind \"Alt a\" { Run \"clave\" \"add\" { floating true; close_on_exit true; }; }\n",
    );
    binds.push_str(&format!(
        "        bind \"Alt c\" {{ MessagePlugin \"file:{wasm}\" {{ name \"clave-toggle\"; }}; }}\n"
    ));
    binds.push_str("        bind \"Alt w\" { CloseTab; }\n");
    // Alt+↓/↑ walk the DISPLAYED list (§6.6 revised 2026-07-08: rows only
    // reorder on user commitments, never on focus — so walking the visible
    // order is stable, no ping-pong). Executor-gated in the plugin: only the
    // active instance (fresh tab set, the bar being read) computes the step.
    binds.push_str(&format!(
        "        bind \"Alt j\" \"Alt Down\" {{ {} }}\n",
        nav("{\\\"dir\\\":\\\"next\\\"}")
    ));
    binds.push_str(&format!(
        "        bind \"Alt k\" \"Alt Up\" {{ {} }}\n",
        nav("{\\\"dir\\\":\\\"prev\\\"}")
    ));
    // True alt-tab (last two focused tabs) is NATIVE — server-side truth.
    // Alt+o = native ToggleTab PLUS a clave-organic pipe: the pipe arms the
    // bounded beacon announce (the newly-active instance's next TabUpdate
    // announces it — rounds 11–12: unbounded self-diagnosed announces
    // stormed; organic switches must be explicitly signalled).
    binds.push_str(&format!(
        "        bind \"Alt o\" {{ ToggleTab; MessagePlugin \"file:{wasm}\" {{ name \"clave-organic\"; }}; }}\n"
    ));
    for n in 1..=9 {
        binds.push_str(&format!(
            "        bind \"Alt {n}\" {{ {} }}\n",
            nav(&format!("{{\\\"row\\\":{n}}}"))
        ));
    }
    format!(
        "// GENERATED by `clave setup` — regenerate, don't hand-edit.\n\
         // §6.8 C8: resurrection is clave-owned (launch + clave open);\n\
         // zellij serialization replays DISCOVERED commands and is off.\n\
         session_serialization false\n\
         // clear-defaults=false: stock zellij behaviour stays; clave only ADDS.\n\
         keybinds clear-defaults=false {{\n\
         \x20   shared_among \"normal\" \"locked\" {{\n{binds}\x20   }}\n\
         }}\n"
    )
}

/// The session layout: EVERY tab gets the bar via default_tab_template
/// (§6.8). Task 9 checkpoint C6 validates the template survives real use;
/// fallback = per-tab panes + a new-tab keybind with an explicit layout.
pub fn layout_kdl(wasm: &str) -> String {
    // split_direction="vertical" goes ON the template node, with `pane` and
    // `children` as DIRECT children (both Task 9 C1 findings):
    // 1. zellij stacks siblings horizontally (rows) by default — without
    //    vertical split the bar is a 30-ROW strip across the top;
    // 2. `children` must NOT be nested inside a wrapper pane: the empty/new-
    //    tab fill path (zellij-utils kdl_layout_parser.rs:1748, v0.44.3) only
    //    inserts the default pane at the template's TOP-LEVEL
    //    external_children_index — it does not recurse — so a nested
    //    `children` yields tabs with no terminal at all.
    format!(
        "// GENERATED by `clave setup` — regenerate, don't hand-edit.\n\
         layout {{\n\
         \x20   default_tab_template split_direction=\"vertical\" {{\n\
         \x20       pane size=30 borderless=true {{\n\
         \x20           plugin location=\"file:{wasm}\"\n\
         \x20       }}\n\
         \x20       children\n\
         \x20   }}\n\
         \x20   tab name=\"clave\" focus=true\n\
         }}\n"
    )
}

/// §6.8 (C8): the launch layout, composed DYNAMICALLY at session-create
/// time. Base = the bar template; store non-empty → ONE eager tab for the
/// most-recent row, baked `clave spawn` (resumes via the jsonl check).
/// Everything else surfaces as dormant bar rows (§6.6).
pub fn launch_layout_kdl(wasm: &str, most_recent: Option<&crate::store::AgentRecord>) -> String {
    let tab = match most_recent {
        // The label is re-sanitized for KDL safety: it can be hook-derived
        // (§6.5) and only add-time labels went through sanitize_label.
        Some(r) => {
            crate::add::tab_node(wasm, &crate::add::sanitize_label(&r.label), &r.uuid, &r.cwd)
        }
        None => "    tab name=\"clave\" focus=true\n".to_string(),
    };
    format!(
        "// GENERATED at launch — §6.8 clave-owned cold start.\n\
         layout {{\n\
         \x20   default_tab_template split_direction=\"vertical\" {{\n\
         \x20       pane size=30 borderless=true {{\n\
         \x20           plugin location=\"file:{wasm}\"\n\
         \x20       }}\n\
         \x20       children\n\
         \x20   }}\n{tab}}}\n"
    )
}

/// Does `zellij list-sessions -n` mention this session at all (live OR
/// EXITED)? An EXITED session must be DELETED before create: `attach
/// --create` would resurrect its serialized state, ignoring `--layout`
/// (§6.8) — replaying pre-C8 discovered commands.
pub fn session_exists(list_output: &str, name: &str) -> bool {
    list_output
        .lines()
        .any(|l| l.split_whitespace().next() == Some(name))
}

/// Additively merge clave's hook registrations into a settings.json value.
/// Never touches existing entries; skips events already carrying our command.
pub fn merge_hooks(settings: &mut serde_json::Value, clave_bin: &str) -> bool {
    // The §6.5 state machine's input events. PermissionRequest/StopFailure
    // are handled IF the CLI sends them, but registration sticks to the
    // documented set; Notification covers the needs-you cases.
    const EVENTS: [&str; 4] = ["UserPromptSubmit", "Stop", "Notification", "SessionEnd"];
    let mut changed = false;
    let hooks = settings
        .as_object_mut()
        .map(|o| o.entry("hooks").or_insert_with(|| serde_json::json!({})))
        .expect("settings.json root must be an object");
    for ev in EVENTS {
        let cmd = format!("{clave_bin} hook {ev}");
        let arr = hooks
            .as_object_mut()
            .expect("hooks must be an object")
            .entry(ev)
            .or_insert_with(|| serde_json::json!([]));
        let entries = arr.as_array_mut().expect("hook event must be an array");
        let present = entries.iter().any(|e| {
            e["hooks"]
                .as_array()
                .is_some_and(|hs| hs.iter().any(|h| h["command"] == serde_json::json!(cmd)))
        });
        if !present {
            entries.push(serde_json::json!({
                "hooks": [ { "type": "command", "command": cmd } ]
            }));
            changed = true;
        }
    }
    changed
}

/// Zellij's permission cache location (verified on this machine in S1).
pub fn permissions_cache_path() -> Result<PathBuf> {
    let home = dirs::home_dir().context("home")?;
    if cfg!(target_os = "macos") {
        Ok(home.join("Library/Caches/org.Zellij-Contributors.Zellij/permissions.kdl"))
    } else {
        Ok(home.join(".cache/zellij/permissions.kdl"))
    }
}

/// Merge our grant into the cache text, preserving everyone else's entries.
/// Format (verified against zellij 0.44.3 PermissionCache::to_string): one
/// quoted-location node per plugin, children = PermissionType names. We
/// remove any existing clave-bar nodes (both key forms) then append fresh
/// ones — replace-not-accumulate keeps re-runs idempotent even when the
/// permission set changes (the S2 lesson).
pub fn merge_permissions_kdl(existing: &str, wasm_abs: &str) -> String {
    let keys = [format!("\"file:{wasm_abs}\""), format!("\"{wasm_abs}\"")];
    let mut out = String::new();
    let mut skipping = false;
    for line in existing.lines() {
        let t = line.trim_start();
        if !skipping && keys.iter().any(|k| t.starts_with(k.as_str())) {
            skipping = true; // drop this node…
        }
        if skipping {
            if t.trim_end().ends_with('}') {
                skipping = false; // …through its closing brace
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    for key in keys {
        out.push_str(&format!("{key} {{\n"));
        for p in BAR_PERMISSIONS {
            out.push_str(&format!("    {p}\n"));
        }
        out.push_str("}\n");
    }
    out
}

/// The whole setup weave. Idempotent by construction — every part merges.
pub fn run_setup() -> Result<()> {
    let dir = data_dir()?;
    std::fs::create_dir_all(&dir)?;
    let wasm = wasm_path()?;
    let wasm_str = wasm.to_str().context("wasm path")?;
    anyhow::ensure!(
        wasm.exists(),
        "{} missing — run `just install` first (it copies the built wasm here)",
        wasm.display()
    );
    std::fs::write(dir.join("config.kdl"), config_kdl(wasm_str))?;
    std::fs::write(dir.join("layout.kdl"), layout_kdl(wasm_str))?;

    // Hooks: read-merge-write $CLAUDE_CONFIG_DIR/settings.json. The path may
    // be a symlink into a dotfiles repo — fs::read/write follow it, which is
    // exactly what we want (§6.5). Routed via claude_config_dir() (not
    // hardcoded home) so `clave dev`'s sandbox (§6.9) merges hooks into its
    // OWN settings.json — else sandbox sessions get no clave hooks and
    // scenario agents never report status. Env unset ⇒ ~/.claude, unchanged.
    let settings_path = crate::env::claude_config_dir()?.join("settings.json");
    let mut settings: serde_json::Value = match std::fs::read(&settings_path) {
        Ok(b) => serde_json::from_slice(&b).context("parsing ~/.claude/settings.json")?,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::json!({}),
        Err(e) => return Err(e).context("reading settings.json"),
    };
    if merge_hooks(&mut settings, "clave") {
        std::fs::write(&settings_path, serde_json::to_vec_pretty(&settings)?)?;
        println!("hooks merged into {}", settings_path.display());
    } else {
        println!("hooks already registered");
    }

    // Permissions pre-seed (§7): merge, preserving other plugins.
    let cache = permissions_cache_path()?;
    if let Some(parent) = cache.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let existing = std::fs::read_to_string(&cache).unwrap_or_default();
    std::fs::write(&cache, merge_permissions_kdl(&existing, wasm_str))?;
    println!("permissions seeded in {}", cache.display());
    Ok(())
}

/// Does `zellij list-sessions -n` output show `name` as a LIVE session?
/// EXITED is not live: attaching resurrects a fresh session whose tab_ids
/// restart from scratch.
pub fn session_is_live(list_output: &str, name: &str) -> bool {
    list_output
        .lines()
        .any(|l| l.split_whitespace().next() == Some(name) && !l.contains("EXITED"))
}

/// Bare `clave`: attach-or-create the dedicated session with OUR config +
/// a DYNAMIC layout (§6.8 C8: eager most-recent tab; serialization is off,
/// so a dead session is deleted, never resurrected).
pub fn launch_session() -> Result<()> {
    let dir = data_dir()?;
    let config = dir.join("config.kdl");
    anyhow::ensure!(config.exists(), "run `clave setup` first");
    let session = crate::env::session_name();
    let list = std::process::Command::new("zellij")
        .args(["list-sessions", "-n"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
        .unwrap_or_default();
    let live = session_is_live(&list, &session);
    if !live {
        // §6.6 hygiene: tab_ids are SESSION-scoped — drop the previous
        // session's timeline + binds before a CREATE.
        crate::store::clear_tab_timeline(&crate::store::store_paths()?)?;
        if session_exists(&list, &session) {
            // Dead-but-serialized (pre-C8 state, or zellij's own cache):
            // delete so attach --create builds from OUR layout.
            let _ = std::process::Command::new("zellij")
                .args(["delete-session", "--force", &session])
                .status();
        }
    }
    // Compose the launch layout from the store (eager most-recent, §6.8).
    // Harmless when live (attach ignores --layout for an existing session).
    let store = crate::store::read_store(&crate::store::store_paths()?)?;
    let most_recent = store.agents.values().max_by_key(|r| r.last_interacted);
    let wasm = wasm_path()?;
    let layout_text = launch_layout_kdl(wasm.to_str().context("wasm path")?, most_recent);
    let layout = std::env::temp_dir().join(format!("clave-launch-{}.kdl", std::process::id()));
    std::fs::write(&layout, layout_text)?;
    crate::evlog::log_event(
        "launch",
        &format!(
            "session={session} live={live} eager={:?}",
            most_recent.map(|r| r.uuid.as_str())
        ),
    );
    use std::os::unix::process::CommandExt;
    let err = std::process::Command::new("zellij")
        .arg("--config")
        .arg(&config)
        .arg("--layout")
        .arg(&layout)
        .args(["attach", "--create", &session])
        .exec();
    Err(anyhow::anyhow!("exec zellij failed: {err}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_is_live_reads_zellij_list_sessions() {
        // `zellij list-sessions -n` lines: `<name> [Created …]`, with
        // ` (EXITED - attach to resurrect)` appended for dead sessions.
        // EXITED counts as NOT live: attach resurrects a FRESH session whose
        // tab_ids restart, so the stale timeline must be cleared then too.
        let out = "chat [Created 5h ago]\nclave [Created 2m ago]\n";
        assert!(session_is_live(out, "clave"));
        let out = "clave [Created 2h ago] (EXITED - attach to resurrect)\n";
        assert!(!session_is_live(out, "clave"));
        // No sessions at all (list-sessions exits non-zero → empty string).
        assert!(!session_is_live("", "clave"));
        // Name must match the whole first token, not a prefix.
        assert!(!session_is_live("clave-dev [Created 1m ago]\n", "clave"));
    }

    #[test]
    fn launch_layout_is_bar_only_when_store_empty() {
        // §6.8 cold start, empty store: today's behavior — template + one
        // plain tab, no agent tabs.
        let kdl = launch_layout_kdl("/w.wasm", None);
        assert!(kdl.contains("default_tab_template"));
        assert!(kdl.contains("tab name=\"clave\" focus=true"));
        assert!(!kdl.contains("\"spawn\""));
    }

    #[test]
    fn launch_layout_eager_loads_only_the_most_recent_row() {
        // §6.8: eagerness of exactly ONE — the most-recent agent resumes
        // focused at launch; every other row stays dormant in the bar.
        let mut r = crate::store::AgentRecord {
            uuid: "u-recent".into(),
            cwd: "/repo/.claude-worktrees/ab".into(), // worktree row: bake ITS cwd
            repo_root: "/repo".into(),
            branch: "main".into(),
            label: "repo · main".into(),
            status: clave_types::Status::Idle,
            last_interacted: 100,
            last_visited: 0,
            worktree: Some("/repo/.claude-worktrees/ab".into()),
            label_source: crate::store::LabelSource::FirstPrompt,
            tab_id: None,
            stale: false,
        };
        let kdl = launch_layout_kdl("/w.wasm", Some(&r));
        assert!(kdl.contains("default_tab_template")); // native new-tabs still barred
        assert!(kdl.contains("\"spawn\" \"u-recent\""));
        assert!(kdl.contains("cwd=\"/repo/.claude-worktrees/ab\""));
        // The eager tab replaces the plain placeholder tab entirely.
        assert!(!kdl.contains("tab name=\"clave\" focus=true"));
        r.label = "x".into(); // silence unused-mut if needed
    }

    #[test]
    fn session_exists_vs_live_distinguish_exited() {
        let out = "clave [Created 2h ago] (EXITED - attach to resurrect)\nother [Created 1m ago]\n";
        assert!(session_exists(out, "clave"));
        assert!(!session_is_live(out, "clave")); // existing fn, unchanged
        assert!(!session_exists(out, "missing"));
    }

    #[test]
    fn hooks_merge_is_additive_and_idempotent() {
        // Existing user hook MUST survive (§6.5: never clobber).
        let mut v: serde_json::Value = serde_json::json!({
            "hooks": { "Stop": [ { "hooks": [ { "type": "command", "command": "my-bell" } ] } ] }
        });
        assert!(merge_hooks(&mut v, "clave"));
        let stops = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stops.len(), 2); // user's + ours
        assert_eq!(stops[0]["hooks"][0]["command"], "my-bell");
        assert_eq!(stops[1]["hooks"][0]["command"], "clave hook Stop");
        // Every event we need is registered.
        for ev in ["UserPromptSubmit", "Notification", "SessionEnd"] {
            assert!(v["hooks"][ev].as_array().is_some(), "{ev} missing");
        }
        // Second run: no change, no duplicates.
        assert!(!merge_hooks(&mut v, "clave"));
        assert_eq!(v["hooks"]["Stop"].as_array().unwrap().len(), 2);
    }

    #[test]
    fn permissions_merge_seeds_both_key_forms_and_preserves_others() {
        let existing = "\"file:/other/plugin.wasm\" {\n    ReadCliPipes\n}\n";
        let merged = merge_permissions_kdl(existing, "/data/clave-bar.wasm");
        // Other plugin untouched:
        assert!(merged.contains("/other/plugin.wasm"));
        // Both key forms present (S1/S2: key form matters):
        assert!(merged.contains("\"file:/data/clave-bar.wasm\""));
        assert!(merged.contains("\"/data/clave-bar.wasm\""));
        // The EXACT §6.6 set under each:
        for p in BAR_PERMISSIONS {
            assert!(
                merged.matches(p).count() >= 2,
                "{p} missing from a key form"
            );
        }
        // Idempotent: re-merging replaces our blocks, not duplicates them.
        let again = merge_permissions_kdl(&merged, "/data/clave-bar.wasm");
        assert_eq!(again.matches("file:/data/clave-bar.wasm").count(), 1);
    }

    #[test]
    fn config_disables_session_serialization() {
        // §6.8 (2026-07-17, C8): resurrection is clave-owned; a serialized
        // session would replay discovered `claude --session-id` commands
        // (create-collision) or mid-tool-call children (pty.rs ppid-priority
        // discovery, v0.44.3 source-verified).
        let kdl = config_kdl("/w.wasm");
        assert!(kdl.contains("session_serialization false"));
    }

    #[test]
    fn generated_kdl_carries_the_wasm_path_and_alt_keys() {
        let cfg = config_kdl("/data/clave-bar.wasm");
        for key in [
            "Alt a", "Alt c", "Alt w", "Alt j", "Alt k", "Alt 1", "Alt 9",
        ] {
            assert!(
                cfg.contains(&format!("bind \"{key}\"")) || cfg.contains(&format!("\"{key}\"")),
                "{key} unbound"
            );
        }
        assert!(cfg.contains("shared_among \"normal\" \"locked\"")); // invariant #6
        assert!(cfg.contains("clave-nav") && cfg.contains("clave-toggle"));
        let lay = layout_kdl("/data/clave-bar.wasm");
        assert!(lay.contains("default_tab_template"));
        assert!(lay.contains("file:/data/clave-bar.wasm"));
        // Regression (Task 9 C1): without the vertical wrapper the bar is a
        // 30-ROW strip on top, not a 30-col LEFT column.
        assert!(lay.contains("split_direction=\"vertical\""));
    }
}
